NDefines.NMilitary.FORT_DEVASTATION_IMPACT = -7.5
NDefines.NMilitary.REVANCHISM_DEVASTATION_IMPACT = -0.015
NDefines.NMilitary.SURRENDER_DEVASTATION_IMPACT = -3
NDefines.NMilitary.CONTROL_DEVASTATION_IMPACT = -2.5