NDefines.NCountry.MONTHLY_LIBERTY_DECREASE = 0.1     			--How much temporary liberty desire changes each month (towards 0 point).
NDefines.NCountry.LIBERTY_DESIRE_ENFORCE_PEACE = 0.1     		--Liberty desire from Enforce Peace in vassal wars.
NDefines.NCountry.LIBERTY_DESIRE_WAR_EXHAUSTION = 1     		--Liberty desire from overlord's war exhaustion (per WE).
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0.25     		--Liberty desire from overlord's mercantilism (per Merc).
NDefines.NCountry.LIBERTY_DESIRE_RELATIVE_POWER = 75     		--Liberty desire from relative power to liege.
NDefines.NCountry.LIBERTY_DESIRE_ADM_EFFICIENCY = 0.2     		--Liberty desire per point of admistrative efficiency (colonies only).
NDefines.NCountry.LIBERTY_DESIRE_DIPLO_TECH = 5     			--Liberty desire per point of diplo tech more than overlord.
NDefines.NCountry.LIBERTY_DESIRE_HISTORICAL_FRIEND = -20    	--Liberty desire from being historical friends.
NDefines.NCountry.LIBERTY_DESIRE_HISTORICAL_RIVAL = 20     		--Liberty desire from being historical rivals.
NDefines.NCountry.LIBERTY_DESIRE_TRUST = -0.2     				--Liberty desire from trust.
NDefines.NCountry.LIBERTY_DESIRE_POSITIVE_OPINION = -0.075    	--Liberty desire from positive opinion.
NDefines.NCountry.LIBERTY_DESIRE_NEGATIVE_OPINION = 0.15     	--Liberty desire from negative opinion.
NDefines.NCountry.LIBERTY_DESIRE_ANNEXATION = 5     			--Liberty desire from being annexed.
NDefines.NCountry.LIBERTY_DESIRE_DIPLOMATIC_REPUTATION = -2 	--Liberty desire from diplomatic reputation.
NDefines.NCountry.LIBERTY_DESIRE_GREAT_POWER_VASSAL = 60    	--Liberty desire from vassal having more than 300 development.
NDefines.NCountry.LIBERTY_DESIRE_HORDE = 15     				--Liberty desire from vassal being a horde.
NDefines.NCountry.LIBERTY_DESIRE_ROYAL_MARRIAGE = -2.5     		--Liberty desire from having RM with overlord.
NDefines.NCountry.LIBERTY_DESIRE_SCUTAGE_OFF = 30     			--Liberty desire from turning off scutage.
NDefines.NCountry.LIBERTY_DESIRE_DEVELOPED_IN_SUBJECT = 0  	    --Liberty desire decrease from overlord developing province in subject.
NDefines.NCountry.LOST_INDEPENDANCE_WAR_LIBERTY_DESIRE = -20 	--How much liberty desire is decreased when an independence war ends.
NDefines.NCountry.TARIFF_LIBERTY_INCREASE = 0.3					--Liberty increase for each % tariffs
NDefines.NCountry.PLACATE_RULERS_PRESTIGE = -25
NDefines.NCountry.PLACATE_RULERS_LIBERTY = -5
NDefines.NCountry.RELATIVE_ON_THRONE_LIBERTY = 10
NDefines.NCountry.RELATIVE_ON_THRONE_NOT_REGENCY_LIBERTY = 25
NDefines.NCountry.ENFORCE_RELIGION_LIBERTY_THRESHOLD = 30
NDefines.NCountry.ENFORCE_CULTURE_LIBERTY = 50
NDefines.NCountry.ENFORCE_CULTURE_LIBERTY_THRESHOLD = 100
NDefines.NCountry.ENFORCE_CULTURE_TAX_MULTIPLIER = 2.5
NDefines.NCountry.SIPHON_INCOME_FRACTION = 0.25
NDefines.NCountry.SIPHON_INCOME_LIBERTY = 15 
NDefines.NCountry.DIVERT_TRADE_FRACTION = 0.75 
NDefines.NCountry.RETURN_LAND_LIBERTY_MULTIPLIER = 1.25 
NDefines.NCountry.COT_DOWNGRADE_LIBERTY_DESIRE = 15 
NDefines.NCountry.SEIZE_TERRITORY_LIBERTY_MULTIPLIER = 5 
NDefines.NCountry.SEIZE_TERRITORY_LIBERTY_THRESHOLD = 100 
NDefines.NCountry.GRANT_PROVINCE_LIBERTY_MULTIPLIER = 0.2
NDefines.NCountry.REPLACE_GOVERNOR_LIBERTY = 5 
NDefines.NCountry.REPLACE_GOVERNOR_LIBERTY_THRESHOLD = 25 
NDefines.NCountry.REPLACE_GOVERNOR_DELAY = 8 
NDefines.NCountry.SEND_SUBSIDIES_MANPOWER_FRACTION = 0.075 
NDefines.NCountry.SUPPORT_LOYALISTS_EXPENSE_MULTIPLIER = 0.3 
NDefines.NCountry.SEND_OFFICERS_MAINTENANCE_MULTIPLIER = 0.33 
NDefines.NCountry.EMBARGO_RIVALS_LIBERTY = 7.5 
NDefines.NCountry.SUPPORT_LOYALISTS_LIBERTY = -15 
NDefines.NCountry.SEND_OFFICERS_LIBERTY = -10 
NDefines.NCountry.DIVERT_TRADE_LIBERTY = 40 
NDefines.NCountry.PROMOTE_INVESTMENTS_TRADEPOWER = 0.5 
NDefines.NCountry.PROMOTE_INVESTMENTS_INFLATION = 0.03 
NDefines.NCountry.SCUTAGE_TAX_FRACTION = 0.5
