NDefines.NEconomy.CARAVAN_FACTOR = 30
NDefines.NEconomy.CARAVAN_POWER_MAX = 100
NDefines.NEconomy.CARAVAN_POWER_MIN = 2
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 20
NDefines.NEconomy.TRADE_PROPAGATE_THRESHOLD = 2
NDefines.NEconomy.LARGE_COLONIAL_NATION_LIMIT = 10
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 20
NDefines.NEconomy.TRADE_PROPAGATE_THRESHOLD = 1
