-- Define overrides when playing on Hard

-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.GREAT_POWER_FRENZY_QUICKSTART = 1
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_MILITARY_RULERS = 0
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_NEIGHBORS = 0
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_PLAYER = 0
NDefines.NAI.GREAT_POWER_ACTIONS_DISABLE_VERSUS_PLAYER = 0
